### PR TITLE
New locale, improved current locales

### PR DESCRIPTION
**Pull request by ShadyMedic**
Previously, I was deploying translation updates to production via a restricted FTP account. Now, when we migrated from Blue's web server, I was told that I need to push updates here. Therefore, I'll be using this branch to add updates whenever a localisation to a language gets completed or verified and submit a pull request after every commit (it shouldn't happen that much though).

- Add Romanian localisation
- Modified translations in pretty much all current localisations

### CODE REVIEW

**Comment by ShadyMedic** [comment]
PLEASE DO NOT DELETE THIS BRANCH

**Comment by deluxghost** [comment]
looks like the English loc files are reverted to an outdated version

example:

image

**Comment by deluxghost** [comment]
uh no, not only English, all languages in this MR are from a same outdated version

**Comment by ShadyMedic** [comment]
I downloaded them from Crowdin. If they are outdated, somebody forgot to upload the new current English locale files there.

**Comment by deluxghost** [comment]
from my translator perspective, the source strings are uploaded to crowdin automatically.

they were up to date before, but crowdin notified me there are new strings today

---

image

---

I can recognize these "new" strings are actually from an outdated version, which match changes of this MR

---

image

---

There should be something wrong in the progress, you may want to find them out

**Comment by ShadyMedic** [comment]
Huh, okay, I guess I'll just all the current languages from Crowdin again and then push them here.

**Comment by ShadyMedic** [comment]
Okay, fixed in #40. If you feel like it, can you check if it's alright now?

**Comment by deluxghost** [comment]
I think it's worse, now every language has these outdated strings

I'm sure English source strings before these MRs are up-to-date, but there are changed in this MR (#38), which triggered changes on crowdin, so if you download files on crowdin, they are all outdated files

**Comment by deluxghost** [comment]
maybe you need to check what has changed in English here https://github.com/FlashpointProject/Flashpoint-Website/pull/38/files

I personally suggest to revert any changes from these MRs before taking any action

**Comment by ShadyMedic** [comment]
Oh crap. Okay, I'll download the English files from before this MR, then overwrite the current files on master with them, which will hopefully update Crowdin back to the up-to-date version and then, I'll start downloading completed translations again, when they're finished.

**Pull request merged**
