### PR TITLE
Update Romanian .LOCALENAME

### PR DESCRIPTION
**Pull request by antoniu200**
Updated translation for Locale Name, as it as wrong. Please include this file for translation on Crowdin.

Sergiu Antoniu Alexa - Romanian Translator and Proofreader

### CODE REVIEW

**Comment by ShadyMedic** [comment]
Hi there, thank you for the fix.

Unfortunatelly, I can't merge this as long as the `.LOCALENAME` file contains more than one line. The newline symbol would also be included in the resulting HTML website and cause an unwanted empty line.

Please, remove the second empty line from the file first.

**Comment by antoniu200** [comment]
Okay, I think it's fine now. Please check and let me know.
Thanks!

**Comment by ShadyMedic** [comment]
I'm afraid that nothing changed, most likely because editing files directly on GitHub might add the linebreak at the end of last line automatically.

Do you think you can try to save the file on your desktop and then push via Git?

**Comment by ShadyMedic** [comment]
The file you uploaded has correct formating, but incorrect name. Can you please rename it on your branch?

**Comment by ShadyMedic** [comment]
Hmm, I'm afraid that the file upload gets rid of the dot in the beginning of the file name anyway.

Are you familiar with using Git locally on your computer?

**Comment by ShadyMedic** [comment]
Perfect. Thank you for your patience.

**Comment by antoniu200** [comment]
Yeah. I just noticed that it actually wasn't GitHub renaming the file, but Windows (or Firefox?) when downloading it.
Oh well. Glad it's solved.
Thanks for merging!

**Pull request merged**
