### PR TITLE
Reverted English source translations back to their up-to-date state

### PR DESCRIPTION
**Pull request by ShadyMedic**
Reverted to commit 35abc45cbcf6870ceb8d525fa75433ec1a1c0b1c

### CODE REVIEW

**Comment by ShadyMedic** [comment]
@deluxghost Can you check this out, before I merge it?

**Comment by deluxghost** [comment]
LGTM

**Comment by deluxghost** [comment]
I have re-added all missing translations of Chinese Simplified on crowdin

**Comment by ShadyMedic** [comment]
Yep, I got an e-mail notification. Not on my PC at the moment, but I'll commit those changes and then create another MR for Chinesee.

What I took from this is, that I simply mustn't modify the English localisation files on master, otherwise Crowdin will download them and add new strings to translate.

**Pull request merged**
